spring:
  datasource:
    url: jdbc:mysql://student.ck6530zwhj6f.ap-south-1.rds.amazonaws.com:3306/student?createDatabaseIfNotExist=true
    username: admin
    password: colombocs
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

